"""
Vectorizes the hero skyline line art (app/assets/hero/skyline.png, an alpha
stencil) into app/components/preloader/skylinePaths.ts so the preloader can
stroke it on with the same dasharray keyframes as the wordmark.

potrace returns each line as a closed outline, so once the stroke has drawn
the outline, fading the fill in reproduces the original artwork exactly.

Usage:  python3 scripts/trace-skyline.py     (needs: pip install pillow potracer)
"""
from pathlib import Path

import numpy as np
import potrace
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "app/assets/hero/skyline.png"
OUT = ROOT / "app/components/preloader/skylinePaths.ts"

TRACE_WIDTH = 3300
ALPHA_THRESHOLD = 40
MIN_SPECK_PX = 12

alpha = Image.open(SRC).convert("RGBA").split()[3]
w, h = alpha.size
alpha = alpha.resize((TRACE_WIDTH, round(TRACE_WIDTH * h / w)), Image.LANCZOS)
alpha = alpha.filter(ImageFilter.MaxFilter(3))
bitmap = np.array(alpha) > ALPHA_THRESHOLD

paths = []
for curve in potrace.Bitmap(bitmap).trace(
    turdsize=MIN_SPECK_PX, alphamax=1.0, opttolerance=0.6
):
    d = [f"M{curve.start_point.x:.0f} {curve.start_point.y:.0f}"]
    xs = [curve.start_point.x]
    for s in curve.segments:
        if s.is_corner:
            d.append(f"L{s.c.x:.0f} {s.c.y:.0f}L{s.end_point.x:.0f} {s.end_point.y:.0f}")
        else:
            d.append(
                f"C{s.c1.x:.0f} {s.c1.y:.0f} {s.c2.x:.0f} {s.c2.y:.0f} "
                f"{s.end_point.x:.0f} {s.end_point.y:.0f}"
            )
        xs.append(s.end_point.x)
    d.append("Z")
    paths.append((sum(xs) / len(xs), "".join(d)))

paths.sort(key=lambda p: p[0])
lines = [
    "/**",
    " * Hero skyline line art as closed outlines, sorted left to right for the",
    " * draw-on stagger. Generated by scripts/trace-skyline.py from",
    " * app/assets/hero/skyline.png — do not edit by hand.",
    " */",
    f'export const SKYLINE_VIEWBOX = "0 0 {alpha.size[0]} {alpha.size[1]}";',
    "",
    "export const SKYLINE_PATHS: readonly string[] = [",
    *[f'  "{d}",' for _, d in paths],
    "];",
    "",
]
OUT.write_text("\n".join(lines))
print(f"wrote {OUT.relative_to(ROOT)}: {len(paths)} paths, {OUT.stat().st_size // 1024} KB")
